### ISSUE TITLE
Is it possible to do HVPP on ATMega32U4?

### ISSUE THREAD

**Issue by geocine** [microtherion/ScratchMonkey#13]
I don't know what I am asking but I am asking anyway, I recently got my ATMega32U4 bricked so hoping that HVPP is a solution.

**Comment by microtherion** [comment]
I'm afraid I haven't been doing any electronics for a couple of years, but judging from the 32u4 data sheet, yes, HVPP should be possible. I assume you've already tried serial programming without success?

**Comment by geocine** [comment]
Yes correct, I suspect I have locked myself out of RESET so looking into this option. If its not too much which part should I look into the datasheet?

**Comment by microtherion** [comment]
Sections 28.5 and 28.6 in the datasheet, "Parallel Programming". `CTRL2-CTRL7` should correspond to `PD2-PD7`, `CTRL0` to `PE6`, `DATA0-DATA7` to `PB0-PB7`.

I did not publish pinouts for SMD parts, because the pins on these are often not accessible enough to bother trying to reprogram them. So what's your plan? Are you desoldering the MCU, or did you install it in a through-hole adapter?

**Comment by geocine** [comment]
I will try to figure out how to do this, thanks for the pointers. The pins your mentioned are all broken out on my custom arduino
